### ISSUE TITLE
check_jmx4perl 1.06 thread_deadlock check fails.

### ISSUE THREAD

**Issue by rhuss** [rhuss/jmx4perl#21]
From https://rt.cpan.org/Public/Bug/Display.html?id=81699 : 

I have just upgraded from v. 0.91 to v. 1.06 and using jolokia 1.06.  The 
thread_deadlock check no longer works.  I'm not passing any arguments to the 
findDeadlockedThreads operation as far as I can tell.  My configuration hasn't 
changed anyway.  I'm not sure if this is a problem in jmx4perl or with jolokia.

Using perl v5.10.0 built for x86_64-linux-thread-multi
Linux 2.6.32.36-0.5.2.3186.0.TEST-default #1 SMP 2011-04-14 10:12:31 +0200 
x86_64 x86_64 x86_64 GNU/Linux

``` bash
<Check thread_deadlock>
    MBean = java.lang:type=Threading
    Operation = findDeadlockedThreads
    Null = no deadlock
    Name = Thread-Deadlock
    String = 1
    Critical = !no deadlock
</Check>
```

``` bash
CRITICAL - Error: 400 java.lang.IllegalArgumentException : Invalid number of 
operation arguments. Operation findDeadlockedThreads on 
java.lang:type=Threading requires 0 parameters, not 1 as 
givenjava.lang.IllegalArgumentException: Invalid number of operation 
arguments. Operation findDeadlockedThreads on java.lang:type=Threading 
requires 0 parameters, not 1 as given
at org.jolokia.handler.ExecHandler.verifyArguments(ExecHandler.java:104)
at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:88)
at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)
at 
org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:86)
at 
org.jolokia.backend.MBeanServerHandler.handleRequest(MBeanServerHandler.java:121)
at 
org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:111)
at 
org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:89)
at 
org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:331)
at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:140)
at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:175)
at 
org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:111)
at org.jolokia.http.AgentServlet$2.handleRequest(AgentServlet.java:286)
at org.jolokia.http.AgentServlet.handle(AgentServlet.java:228)
at org.jolokia.http.AgentServlet.doPost(AgentServlet.java:200)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at 
org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
at 
org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
at 
org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
at 
org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
at 
org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:567)
at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:598)
at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
at java.lang.Thread.run(Thread.java:619)
```

**Comment by formorer** [comment]
I have the same problem on Debian with 1.13, we have a multi check here: 

```
 <MultiCheck default_basic>
    Check = filedescriptor($0,$1)
    Check = thread_count($2,$3)
    Check = memory_heap($4,$5)
    Check = memory_non_heap($6,$7)
    Check = thread_deadlock
 </MultiCheck>
```

Calling it with: ` /usr/lib/nagios/plugins/check_jmx4perl '--config' '/tmp/default.cfg' '-u' 'http://XXXX:8181/jolokia' '--check' 'default_basic' '90 80' '750 700' '98 95' '95 90'` gives us the following error: 

[5] UNKNOWN Thread-Deadlock: Error: 400 java.lang.IllegalArgumentException : Invalid number of operation arguments. Operation findDeadlockedThreads on java.lang:type=Threading requires 0 parameters, not 4 as given

as it seems all parameters get into the Thread-Deadlock function which results into the error.
